### ISSUE TITLE
Development installation issues

### ISSUE THREAD

**Issue by emptytank** [katanaml/streamlit-sparrow-labeling-comp#1]
Hi Andrej,

The Streamlit Sparrow Labelling Component looks like a really great tool! I was interested in trying it out but had a few issues running the JS and Python development. Any thoughts on how to resolve?

**1.  JS Side: npm install**

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: react-scripts@3.4.1
> npm ERR! Found: typescript@4.8.4
> npm ERR! node_modules/typescript
> npm ERR!   typescript@"~4.8.4" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@3.4.1
> npm ERR! node_modules/react-scripts
> npm ERR!   react-scripts@"3.4.1" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: typescript@3.9.10
> npm ERR! node_modules/typescript
> npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@3.4.1
> npm ERR!   node_modules/react-scripts
> npm ERR!     react-scripts@"3.4.1" from the root project

**2. Python Side: conda create -n streamlit-sparrow-labeling python=3.11**

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - python=3.11
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by abaranovskis-redsamurai** [comment]
Hey,

If you want to try it out in your app, you can install prebuilt component from PIP:

```
pip install streamlit-sparrow-labeling
```

You need to build with NPM and Python, if you want to change the component and add functionality.

Which versions of NPM and Node you are using? I works for me with these versions:

```
NPM =  8.3.1
Node = v16.13.1
```

For Python part, I'm not using Conda, can't comment on this. I'm using plain Python 3.11 (https://www.python.org/downloads/) installation and creating Python environment in PyCharm IDE. Btw., 3.11 is not necessary, you can use it with Python 3.8+
